export const studyTestData = [
  {
    Question: "Elemental Serenity",
    Option:
      "It feels cool and expansive in my hand, like the stillness of a frozen lake or the depths of the ocean.",
    Total: 22,
    Male: 28,
    Female: 16,
    "Mindset 1 of 2": 24,
    "Mindset 2 of 2": 21,
    "Mindset 1 of 3": 20,
    "Mindset 2 of 3": 22,
    "Mindset 3 of 3": 25,
    "Prelim Q1": 21,
    "Prelim Q2": 26,
    "Prelim Q3": 21,
    "Prelim Q4": 26,
    "Prelim Q5": 20,
    "Prelim Q6": 33,
    "Prelim Q7": 23,
    "Prelim Q8": 26,
  },
  {
    Question: "Elemental Serenity",
    Option:
      "The surface is frosted and mist-like, with a glacial purity that feels calm and restorative.",
    Total: 18,
    Male: 17,
    Female: 20,
    "Mindset 1 of 2": 19,
    "Mindset 2 of 2": 18,
    "Mindset 1 of 3": 15,
    "Mindset 2 of 3": 28,
    "Mindset 3 of 3": 19,
    "Prelim Q1": 17,
    "Prelim Q2": 24,
    "Prelim Q3": 17,
    "Prelim Q4": 24,
    "Prelim Q5": 15,
    "Prelim Q6": 28,
    "Prelim Q7": 16,
    "Prelim Q8": 44,
  },
  {
    Question: "Elemental Serenity",
    Option:
      "It flows without edges, shaped by water and air, connecting me to untouched nature.",
    Total: 18,
    Male: 23,
    Female: 12,
    "Mindset 1 of 2": 22,
    "Mindset 2 of 2": 14,
    "Mindset 1 of 3": 18,
    "Mindset 2 of 3": 15,
    "Mindset 3 of 3": 25,
    "Prelim Q1": 16,
    "Prelim Q2": 27,
    "Prelim Q3": 16,
    "Prelim Q4": 27,
    "Prelim Q5": 19,
    "Prelim Q6": 15,
    "Prelim Q7": 7,
    "Prelim Q8": 15,
  },
  {
    Question: "Elemental Serenity",
    Option:
      "The pale blue and silvery tones look like crystalline water under a serene sky.",
    Total: 23,
    Male: 26,
    Female: 20,
    "Mindset 1 of 2": 23,
    "Mindset 2 of 2": 24,
    "Mindset 1 of 3": 15,
    "Mindset 2 of 3": 22,
    "Mindset 3 of 3": 37,
    "Prelim Q1": 25,
    "Prelim Q2": 18,
    "Prelim Q3": 25,
    "Prelim Q4": 18,
    "Prelim Q5": 24,
    "Prelim Q6": 25,
    "Prelim Q7": 23,
    "Prelim Q8": 16,
  },
  {
    Question: "Sunburst Vitality",
    Option:
      "It feels bold and geometric in my hand, like a burst of energy drawn from nature.",
    Total: 23,
    Male: 23,
    Female: 23,
    "Mindset 1 of 2": 28,
    "Mindset 2 of 2": 17,
    "Mindset 1 of 3": 31,
    "Mindset 2 of 3": 25,
    "Mindset 3 of 3": 11,
    "Prelim Q1": 23,
    "Prelim Q2": 27,
    "Prelim Q3": 23,
    "Prelim Q4": 27,
    "Prelim Q5": 20,
    "Prelim Q6": 32,
    "Prelim Q7": 28,
    "Prelim Q8": 32,
  },
  {
    Question: "Sunburst Vitality",
    Option:
      "The texture feels fresh and bright, like the surface of citrus fruit or sunlit botanicals.",
    Total: 17,
    Male: 18,
    Female: 16,
    "Mindset 1 of 2": 16,
    "Mindset 2 of 2": 18,
    "Mindset 1 of 3": 16,
    "Mindset 2 of 3": 27,
    "Mindset 3 of 3": 10,
    "Prelim Q1": 15,
    "Prelim Q2": 25,
    "Prelim Q3": 15,
    "Prelim Q4": 25,
    "Prelim Q5": 17,
    "Prelim Q6": 10,
    "Prelim Q7": 26,
    "Prelim Q8": 40,
  },
  {
    Question: "Sunburst Vitality",
    Option:
      "Sharp shapes and lively details radiate vitality, like striking bursts of freshness.",
    Total: 20,
    Male: 21,
    Female: 18,
    "Mindset 1 of 2": 26,
    "Mindset 2 of 2": 12,
    "Mindset 1 of 3": 29,
    "Mindset 2 of 3": 19,
    "Mindset 3 of 3": 9,
    "Prelim Q1": 20,
    "Prelim Q2": 21,
    "Prelim Q3": 20,
    "Prelim Q4": 21,
    "Prelim Q5": 17,
    "Prelim Q6": 17,
    "Prelim Q7": 35,
    "Prelim Q8": 36,
  },
  {
    Question: "Sunburst Vitality",
    Option:
      "The colors are energizing—sunny yellows and bright greens that feel full of life.",
    Total: 20,
    Male: 19,
    Female: 21,
    "Mindset 1 of 2": 25,
    "Mindset 2 of 2": 12,
    "Mindset 1 of 3": 26,
    "Mindset 2 of 3": 12,
    "Mindset 3 of 3": 17,
    "Prelim Q1": 19,
    "Prelim Q2": 22,
    "Prelim Q3": 19,
    "Prelim Q4": 22,
    "Prelim Q5": 20,
    "Prelim Q6": 14,
    "Prelim Q7": 25,
    "Prelim Q8": 26,
  },
  {
    Question: "Fresh & Vital",
    Option:
      "It stands upright and vibrant, like something pulsing with nature’s energy.",
    Total: 19,
    Male: 18,
    Female: 18,
    "Mindset 1 of 2": 15,
    "Mindset 2 of 2": 20,
    "Mindset 1 of 3": 16,
    "Mindset 2 of 3": 24,
    "Mindset 3 of 3": 12,
    "Prelim Q1": 18,
    "Prelim Q2": 23,
    "Prelim Q3": 18,
    "Prelim Q4": 23,
    "Prelim Q5": 21,
    "Prelim Q6": 8,
    "Prelim Q7": 24,
    "Prelim Q8": 39,
  },
  {
    Question: "Fresh & Vital",
    Option:
      "The texture is organic, like foaming washes and leafy, natural surfaces.",
    Total: 14,
    Male: 9,
    Female: 17,
    "Mindset 1 of 2": 11,
    "Mindset 2 of 2": 18,
    "Mindset 1 of 3": 12,
    "Mindset 2 of 3": 24,
    "Mindset 3 of 3": 6,
    "Prelim Q1": 13,
    "Prelim Q2": 16,
    "Prelim Q3": 13,
    "Prelim Q4": 16,
    "Prelim Q5": 16,
    "Prelim Q6": 6,
    "Prelim Q7": 5,
    "Prelim Q8": 40,
  },
  {
    Question: "Fresh & Vital",
    Option:
      "It feels shaped by fresh juice and water, full of movement and renewal.",
    Total: 16,
    Male: 14,
    Female: 17,
    "Mindset 1 of 2": 14,
    "Mindset 2 of 2": 18,
    "Mindset 1 of 3": 12,
    "Mindset 2 of 3": 32,
    "Mindset 3 of 3": 6,
    "Prelim Q1": 15,
    "Prelim Q2": 21,
    "Prelim Q3": 15,
    "Prelim Q4": 21,
    "Prelim Q5": 18,
    "Prelim Q6": 9,
    "Prelim Q7": 22,
    "Prelim Q8": 28,
  },
  {
    Question: "Fresh & Vital",
    Option:
      "The green is lush and full of vitality, like plants bursting with life.",
    Total: 19,
    Male: 17,
    Female: 20,
    "Mindset 1 of 2": 19,
    "Mindset 2 of 2": 18,
    "Mindset 1 of 3": 20,
    "Mindset 2 of 3": 21,
    "Mindset 3 of 3": 16,
    "Prelim Q1": 19,
    "Prelim Q2": 17,
    "Prelim Q3": 19,
    "Prelim Q4": 17,
    "Prelim Q5": 19,
    "Prelim Q6": 18,
    "Prelim Q7": 24,
    "Prelim Q8": 17,
  },
  {
    Question: "Playful Purity",
    Option:
      "It feels light and playful in my hand, with a shape that adds joy to staying clean.",
    Total: 19,
    Male: 17,
    Female: 22,
    "Mindset 1 of 2": 24,
    "Mindset 2 of 2": 13,
    "Mindset 1 of 3": 26,
    "Mindset 2 of 3": 21,
    "Mindset 3 of 3": 6,
    "Prelim Q1": 20,
    "Prelim Q2": 18,
    "Prelim Q3": 20,
    "Prelim Q4": 18,
    "Prelim Q5": 17,
    "Prelim Q6": 24,
    "Prelim Q7": 26,
    "Prelim Q8": 28,
  },
  {
    Question: "Playful Purity",
    Option:
      "Smooth and creamy with a soft shine, it feels gentle and refreshing to touch.",
    Total: 12,
    Male: 4,
    Female: 21,
    "Mindset 1 of 2": 21,
    "Mindset 2 of 2": 1,
    "Mindset 1 of 3": 24,
    "Mindset 2 of 3": 10,
    "Mindset 3 of 3": -3,
    "Prelim Q1": 12,
    "Prelim Q2": 12,
    "Prelim Q3": 12,
    "Prelim Q4": 12,
    "Prelim Q5": 8,
    "Prelim Q6": 23,
    "Prelim Q7": 16,
    "Prelim Q8": 24,
  },
  {
    Question: "Playful Purity",
    Option:
      "There’s a bit of transparency and soft curves that make it feel unexpected and fun.",
    Total: 18,
    Male: 13,
    Female: 23,
    "Mindset 1 of 2": 24,
    "Mindset 2 of 2": 10,
    "Mindset 1 of 3": 27,
    "Mindset 2 of 3": 14,
    "Mindset 3 of 3": 9,
    "Prelim Q1": 19,
    "Prelim Q2": 17,
    "Prelim Q3": 19,
    "Prelim Q4": 17,
    "Prelim Q5": 21,
    "Prelim Q6": 9,
    "Prelim Q7": 12,
    "Prelim Q8": 28,
  },
  {
    Question: "Playful Purity",
    Option:
      "Pastels with splashes of bright tones make it feel joyful and expressive.",
    Total: 18,
    Male: 14,
    Female: 21,
    "Mindset 1 of 2": 27,
    "Mindset 2 of 2": 4,
    "Mindset 1 of 3": 26,
    "Mindset 2 of 3": 10,
    "Mindset 3 of 3": 11,
    "Prelim Q1": 19,
    "Prelim Q2": 14,
    "Prelim Q3": 19,
    "Prelim Q4": 14,
    "Prelim Q5": 21,
    "Prelim Q6": 3,
    "Prelim Q7": 16,
    "Prelim Q8": 30,
  },
];
